language: python3
install:
- lsb_release -a
- sudo apt-get update
- sudo apt-get install python3-dbus lvm2
- sudo mkdir -vp /pseudo
- sudo dd if=/dev/zero of=/pseudo/d1.img bs=1 count=0 seek=8G
- sudo dd if=/dev/zero of=/pseudo/d2.img bs=1 count=0 seek=8G
- sudo dd if=/dev/zero of=/pseudo/d3.img bs=1 count=0 seek=8G
- sudo dd if=/dev/zero of=/pseudo/d4.img bs=1 count=0 seek=8G
- sudo dd if=/dev/zero of=/pseudo/d5.img bs=1 count=0 seek=8G
# Oops add the loopback
- sudo losetup -f /pseudo/d1.img
- sudo losetup -f /pseudo/d2.img
- sudo losetup -f /pseudo/d3.img
- sudo losetup -f /pseudo/d4.img
- sudo losetup -f /pseudo/d5.img
- sudo pvcreate /dev/loop0
- sudo pvcreate /dev/loop1
- sudo pvcreate /dev/loop2
- sudo pvcreate /dev/loop3
- sudo pvcreate /dev/loop4
- lsblk
script:
- ./hello.py
